[build]
builder = "dockerfile"
dockerfilePath = "whatsapp-mcp-server/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
MCP_HOST = "0.0.0.0"
MCP_PORT = "${{ PORT }}"
BRIDGE_URL = "${{ RAILWAY_PUBLIC_DOMAIN }}"
PORT = "3000"
