services:
  - type: web
    name: whatsapp-bridge
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release
    # Auto-deploy when you push to main branch
    autoDeploy: true